### ISSUE TITLE
Getting error "e.headers is not a function"

### ISSUE THREAD

**Issue by adyckman** [andig/grafana-darksky#12]
Running Grafana Grafana v6.7.0-beta1 (eaaca91f25) in Docker; added the Dark Sky plugin via grafana-cli.  When I enter my API key and lat/long values and try to Save & Test, I get an error:

> e.headers is not a function

When I view the docker container log, the last entry reads:

> t=2020-03-20T20:38:36+0000 lvl=info msg=Requesting logger=data-proxy-log url=https://api.darksky.net/forecast/(api key redacted)/(lat redacted),(long redacted)

Unsure what could be the problem here.  Any suggestions?

**Comment by andig** [comment]
Try upgrading Grafana. Sounds a bit like in the vicinity of https://github.com/grafana/grafana/pull/22778

**Comment by Krixa** [comment]
same issue here, running grafana 6.7.1

**Comment by CharlesCage** [comment]
Same here, also running 6.7.1. But it looks like 22778 fix hasn't been released yet. Will watch here for news. :)

**Comment by matthieu100** [comment]
Same here ... can not extract any data of dark sky ... any one hase a good tutoriel to fixed this issue ?

**Comment by andig** [comment]
Seems #22778 has been released as per https://github.com/grafana/grafana/pull/22893. I can only suggest to investigate and open a ticket with Grafana.

**Comment by CharlesCage** [comment]
Totally understand if I’m missing something, but at least a couple of us in
the thread are on .7.1, so are still seeing the problem after the release.
Will open a ticket over there. :)

**Comment by matthieu100** [comment]
Was the link beetwin  dark sky and garfana working in the prevuse verrtion of grafana? 7.0?

**Comment by matthieu100** [comment]
still getting the error after an up-date (repare) of grafana ? can't understand how to overcome this issue... @andig did it work for you ? 
thanks

**Comment by andig** [comment]
I've just published the release, sorry for the delay. It still needs a PR against https://github.com/grafana/grafana-plugin-repository- would be great to get help with that.

**Comment by blaetti** [comment]
Thanks. I've updated the plugin and now it works.

**Comment by CharlesCage** [comment]
Just wanted to say thanks. I'm completely resolved now as well.

**Comment by matthieu100** [comment]
Just wanted to say thanks for your help! It si running grate! 
I got just quick question: is the format of the query blocked by dark sky ?: 
![image](https://user-images.githubusercontent.com/62599123/78346335-32c14c00-759f-11ea-8dbb-280646298914.png)
I wanted to do some modification on the data, like for instance changing the unit of the wind to knots (kn) but could not find a way to changer the code of the queries...

**Comment by andig** [comment]
> I wanted to do some modification on the data, like for instance changing the unit of the wind to knots (kn) but could not find a way to changer the code of the queries...

See https://github.com/andig/grafana-darksky, that's in the datasource options
