### ISSUE TITLE
Save & Test reverses lat and long

### ISSUE THREAD

**Issue by doctorkb** [andig/grafana-darksky#13]
When I edit the datasource, entering the latitude in the latitude box and longitude in the longitude box, then click "Save & Test", the request (per the grafana-server syslog entry) is to:

https://api.darksky.net/forecast/APIKEY/LONG,LAT

which fails.  If I reverse the entries (put the latitude in the longitude box and vice versa), it passes, though we get the separate known issue of t.headers.

**Comment by andig** [comment]
Got it! The mistake is with https://github.com/andig/grafana-darksky/pull/9, https://github.com/andig/grafana-darksky/pull/9/files#diff-d08c5e2aaf65d640a9e2fce1af5b062cR215.

/cc @mistadave would you care to fix?

**Comment by mistadave** [comment]
@doctorkb can you give me some information about in which Grafana Version you are using this plugin?

@andig I'll dive into this problem. I think it's correlated with the big changes the Grafana Team has done in version 6.7

**Comment by doctorkb** [comment]
@mistadave I'm on 6.7.1

There is the extra issue of the "t.headers is not a function" error now, but that seems to be tied to the Grafana upgrade that they haven't resolved.

**Comment by andig** [comment]
> I think it's correlated with the big changes the Grafana Team has done in version 6.7

Don't think so. Please see linked line above- they're just swapped in your PR ;)

**Comment by andig** [comment]
> I think it's correlated with the big changes the Grafana Team has done in version 6.7

Don't think so. Please see linked line above- they're just swapped in your PR ;)

    let url = `${this.apiUrl}/${this.lon},${this.lat}`;

**Comment by mistadave** [comment]
So i checked the documentation of the Dark Sky API. And you're right, it messed this up. I'll fix it aswell.

From the doc:

Forecast Request
```
https://api.darksky.net/forecast/[key]/[latitude],[longitude]
```
