### ISSUE TITLE
Weather metrics that use percentages as the unit are being incorrectly displayed

### ISSUE THREAD

**Issue by BasilHall** [andig/grafana-darksky#2]
Weather metrics that use percentages, such as humidity and precipitation probability are being returned as a decimal from 0 to 1, rather than a percent. The data returned for these metrics simply needs to be multiplied by 100 and then it would function correctly.

**Comment by andig** [comment]
Not sure what you're suggesting here. The plugin is delivering the values that the darksky API provides. Should we multiply everything that is named `/(Percent|Probability)$/` by 100?

**Comment by BasilHall** [comment]
Agreed. The DarkSky API appears to deliver its percentages as a decimal from 0 to 1, and Grafana does not internally multiply by 100 when the "percentage" unit is selected, because it is expecting that this has been done already. 

When these metrics are displayed or plotted with "percent" as the unit, they show up as something between 0% and 1% all of the time, which is definitely misleading, especially when decimals are turned off (ends up showing 0% essentially all of the time). I think multiplying everything named /(Percent|Probability)$/ by 100 should resolve the issue entirely, unless I am missing something obvious. Is there a reason or solution that I am not thinking of that would make this a non-issue?

**Comment by andig** [comment]
It have the feeling this is too simple. E.g. `humidity` is also a percent value I think but doesn't carry it in its name. Seems we'd need an exhaustive list of attributes to multiply in order to fix this.

**Comment by BasilHall** [comment]
I think this is probably correct. How difficult would it be to manually make this attribute list? I have looked at the data structure returned by a query a little bit, and at while there is a decent number of parameters it did look manageable. Is there something more complicated about this than meets the eye at first glance?

**Comment by andig** [comment]
Don't think so. Pleas feel free to suggest a list. Other course of action might be to ask Grafana adding a new Percent type that would work on [0..1] data to not have this issue in every other datasource.

**Comment by tedpearson** [comment]
0-1 percentages are a thing in grafana, this could be closed:
![image](https://user-images.githubusercontent.com/1477390/74208429-88d5db00-4c51-11ea-87a2-21f7bbb71f97.png)
