### ISSUE TITLE
can't use alerts 

### ISSUE THREAD

**Issue by ratio91** [andig/grafana-darksky#4]
Whenever I try to set alerts in Grafana, the following error appears:

```error:"tsdb.HandleRequest() error Could not find executor for data source type: andig-darksky-datasource"```

Do I need some additional plugins?

**Comment by andig** [comment]
Alerts only work with backend datasources.

**Comment by ratio91** [comment]
okay, so if I dump the darksky data into an influxdb first, then alerts should work, correct?
