### ISSUE TITLE
[Feature Request] Move the Geolocation code into the rendering engine

### ISSUE THREAD

**Issue by proffalken** [andig/grafana-darksky#6]
Hi,

We're using Grafana to provide some of the basic dashboards for a farm management solution.

It would be really useful if we could set the location for the DarkSky api on a "per graph" basis, ideally fed from an existing lat/long variable provided by a device in the database.

As an example, for the `TrackMap` plugin, we're currently using the following query:

```
SELECT median("latitude"), median("longitude") FROM "gps_location_1" WHERE ("device_name" = 'MyDevice') AND $timeFilter GROUP BY time($interval)
```

It would be amazing if we could take the output of that query and use it to set the lat/long of the DarkSky plugin.

**Comment by krisfertig** [comment]
+1

**Comment by andig** [comment]
I guess we could easily support variables for that purpose- would you be able to populate those?

**Comment by proffalken** [comment]
Yeah, I don't see why not. 

The device ID is stored as a value within the influx database, so calling a query against Darksky for that particular device's lat/long *should* be possible...

**Comment by andig** [comment]
Would #9 work for you? Pleas note there is a current bug with lat/lon swapped.

**Comment by proffalken** [comment]
Yeah, should do, thanks
